#!/usr/bin/env node

var webpack = require('webpack');
var config = require('./webpack.config.js');
var applescript = require('applescript');

const script = `tell application "Google Chrome"
    set atab to active tab of front window
    if (URL of atab contains "workbench") then
        tell atab
            execute javascript "( function () { var iframe = document.querySelector('[id$=configurator]');  var src = iframe.src;  if (src.indexOf('rnd=') === -1) { iframe.src = iframe.src += '&rnd=' + (new Date).getTime(); } else { var rnd = 'rnd=' + (new Date).getTime(); iframe.src = src.replace(/rnd=\d+/, rnd); } })();"
        end tell
    end if
end tell`;

var compiler = webpack(config);

compiler.watch({}, (err, stats) => {
    console.log(err);
    console.log(stats.toString({
        colors: true,
        modules: false,
        children: false,
        chunks: false,
        chunkModules: false,
        warnings: false
    }));
    applescript.execString(script, function(err, rtn) {
    });
});


/*
var webpackDevServer = require('webpack-dev-server');
var server = new webpackDevServer(compiler, {
    hot: true
});

console.log('server run at: http://127.0.0.1:8002');
server.listen(8002);
*/